---
project_name: prometheus_bigquery_remote_storage_adapter
version: 2
env:
  - CGO_ENABLED=0
builds:
  - ldflags:
    - "-X {{.Env.VERSION_PKG}}.Branch={{.Env.BRANCH}}"
    - "-X {{.Env.VERSION_PKG}}.BuildDate={{.Env.DATE}}"
    - "-X {{.Env.VERSION_PKG}}.GitSHA1={{.Env.COMMIT}}"
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
archives:
- name_template: >-
    {{- .ProjectName }}_
    {{- .Version }}_
    {{- title .Os }}_
    {{- if eq .Arch "amd64" }}x86_64
    {{- else if eq .Arch "386" }}i386
    {{- else }}{{ .Arch }}{{ end }}
checksum:
  name_template: 'checksums.txt'
snapshot:
  version_template: "{{.Tag}}-next"
changelog:
  disable: true
